custombucket = "proj-bucket"
table = "intellipaat"
databasehost = "proj-database.cmod5rwumqpl.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "dikshant"
s3database = "intellipaat"
kapp = "http://20.0.2.6:31000"
